server:
  port: 3000
  jetty:
    acceptors: 2
    selectors: 4
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  name: David
  logApi: true

logging:
  level:
    web: DEBUG


spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    addMappings: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: default
          dataSource:
            default:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/quartz
              user: root
              password: example
              maxConnections: 5
          plugin:
            jobInitializer:
              class: org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin  
              fileNames: quartz_job.xml
              failOnFileNotFound: true    
              scanInterval: 10  
              # wrapInUserTransaction: false