server:
  port: 3000
  jetty:
    acceptors: 2
    selectors: 4
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  name: David
  logApi: true

# logging:
#   level:
#     web: DEBUG


spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    addMappings: false
  datasource:
    username: root
    password: example
    url: jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # quartz:
  #   properties:
  #     org:
  #       quartz:
  #         plugin:
  #           jobInitializer:
  #             class: org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin  
  #             fileNames: quartz_job.xml
  #             failOnFileNotFound: true    
  #             scanInterval: 10  

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
