server:
  port: 3000
  servlet:
    context-path: /api
  jetty:
    acceptors: 2
    selectors: 4
  error:
    # path: /swagger-ui.html
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  name: David
  logApi: true
